name: Docker Build for Feature or Fix Branches

on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract Docker tag from branch name
      id: extract_tag
      run: |
        BRANCH="${GITHUB_REF#refs/heads/}"
        TAG="${BRANCH#*/}"  # Strip 'feature/' or 'fix/'
        echo "Using Docker tag: $TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/no-code-architects-toolkit:${{ steps.extract_tag.outputs.tag }}
