name: Docker Build for Feature, Fix, and Testing Branches

on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'
      - 'testing'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract repo name and Docker tag
      id: extract
      run: |
        REPO_NAME="${GITHUB_REPOSITORY##*/}"
        BRANCH="${GITHUB_REF#refs/heads/}"

        if [ "$BRANCH" = "testing" ]; then
          TAG="testing"
        else
          TAG="${BRANCH#*/}"  # Strip 'feature/' or 'fix/'
        fi

        echo "Repository name: $REPO_NAME"
        echo "Docker tag: $TAG"
        echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Build and push Docker image with cache
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.extract.outputs.repo_name }}:${{ steps.extract.outputs.tag }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.extract.outputs.repo_name }}:cache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.extract.outputs.repo_name }}:cache,mode=max
